name: Release LaTeX build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: "journal.tex"
      - name: Upload PDF file
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
